export const Images = {
  heroStar: "/assets/landing-assets/svg/hero-star.svg",
  logoImage: "/assets/landing-assets/svg/logo.svg",
  heroImg: "/assets/landing-assets/png/nav-logo.png",
  heroBottomLayer: "/assets/landing-assets/svg/hero-layer-bottom.svg",
  heroLeftPot: "/assets/landing-assets/svg/hero-left-side-pot.svg",
  heroRightPot: "/assets/landing-assets/svg/hero-right-side-pot.svg",
  heroLeftIcon: "/assets/landing-assets/png/hero-left-icon.png",
  heroRightIcon: "/assets/landing-assets/png/hero-right-icon.png",
  workoutChatImg: "/assets/landing-assets/png/workout-chat-img.png",
  partnerIconOne: "/assets/landing-assets/webp/partner-icon-1.webp",
  partnerIconTwo: "/assets/landing-assets/webp/partner-icon-2.webp",
  partnerIconThree: "/assets/landing-assets/webp/partner-icon-3.webp",
  partnerIconFour: "/assets/landing-assets/webp/partner-icon-4.webp",
  partnerIconFive: "/assets/landing-assets/webp/partner-icon-5.webp",
  img_logo_footer: "/assets/landing-assets/svg/logoFooter.svg",
  msgIcon: "/assets/landing-assets/svg/Gmail-logo.svg",
  telIcon: "/assets/landing-assets/svg/tele-logo.svg",
  workoutIcon: "/assets/landing-assets/svg/workout-img.svg",
  trackingFeedbackImg: "/assets/landing-assets/png/tracking-main-img.png",
  checkIcon: "/assets/landing-assets/svg/check_icon.svg",
  feedbackVectorImg: "/assets/landing-assets/png/feedback_top-vecter.png",
  reportingImg: "/assets/landing-assets/png/Report-main-img.png",
  reportingVectorImg:
    "/assets/landing-assets/png/reporting-analytis-bottom-vecter.png",
  trackingImg: "/assets/landing-assets/png/tracking-with-graff.png",
  sliderBgImg: "/assets/landing-assets/png/exercies-slider-bg-img.png",
  sliderPersonOne: "/assets/landing-assets/png/exercies-slider-men.png",
  sliderPersonTwo: "/assets/landing-assets/png/exercies-slider-men2.png",
  clintReview1: "/assets/landing-assets/webp/yoomi-review-by-clint-1.webp",
  commaUp: "/assets/landing-assets/svg/comma_upper.svg",
  commaDown: "/assets/landing-assets/svg/comma_lower.svg",
  starGroup: "/assets/landing-assets/svg/StarGrup.svg",
  ourPlateFormSide: "/assets/landing-assets/png/ourPlateForm-right-img.png",
  plateFormBoxVector: "/assets/landing-assets/png/plateForm_box_vector.png",
  committedLogoHippa: "/assets/landing-assets/webp/committedLogoHippa.webp",
  committedLogoFda: "/assets/landing-assets/webp/committedLogoFDA.webp",
  committedLogoApta: "/assets/landing-assets/webp/committedLogoApta.webp",
  yomiFooterNewsCharacter:
    "/assets/landing-assets/svg/Yommi-News-Character.svg",
  yomiAboutPlusICO: "/assets/landing-assets/svg/Yomi-plus-ico-AboutUs.svg",
  yomiAboutPlusICOsec:
    "/assets/landing-assets/svg/Yomi-plus2nd-ico-AboutUs.svg",
  Yoomi_translatecard_icon:
    "/assets/landing-assets/svg/Yoomi_translatecard_icon.svg",
  footerSideIcon: "/assets/landing-assets/svg/footerIcon.svg",
  knowMoreSlide1: "/assets/landing-assets/png/know-more-slide-1.png",
  knowMoreSlide2: "/assets/landing-assets/png/know-more-slide-2.png",
  knowMoreSlide3: "/assets/landing-assets/png/know-more-slide-3.png",
  knowMoreSlide4: "/assets/landing-assets/png/know-more-slide-4.png",
  knowMoreBigSeminar: "/assets/landing-assets/png/know_more-big-img.png",
  knowMoreBigSeminar2: "/assets/landing-assets/png/know_more-big-img-2.png",
  forecastIcon: "/assets/landing-assets/svg/forecastIcon.svg",
  // about pages images
  aboutTopSlider1: "/assets/about-assets/webp/about-top-slider1.webp",
  aboutTopSlider2: "/assets/about-assets/webp/about-top-slider2.webp",
  headerIcon1: "/assets/about-assets/png/header-icon.png",
  headerIcon2: "/assets/about-assets/png/header-icon-2.png",
  commonIcon: "/assets/about-assets/png/common-hero-img-1.png",
  commonIcon2: "/assets/about-assets/png/common-hero-img-2.png",
  // out team
  ourTeamCard1: "/assets/about-assets/png/our_team_card1.png",
  ourTeamCard2: "/assets/about-assets/png/our_team_card2.png",
  ourTeamCard3: "/assets/about-assets/png/our_team_card3.png",
  ourTeamCard4: "/assets/about-assets/png/our_team_card4.png",
  ourTeamCard5: "/assets/about-assets/png/our_team_card5.png",
  ourTeamCard6: "/assets/about-assets/png/our_team_card6.png",
  ourTeamCard7: "/assets/about-assets/png/our_team_card7.png",
  ourTeamCard8: "/assets/about-assets/png/our_team_card8.png",
  ourTeamCard9: "/assets/about-assets/png/our_team_card9.png",
  ourTeamCard10: "/assets/about-assets/png/our_team_card10.png",
  ourTeamCard11: "/assets/about-assets/png/our_team_card11.png",
  ourTeamCard12: "/assets/about-assets/png/our_team_card12.png",
  ourTeamCard13: "/assets/about-assets/png/our_team_card13.png",
  ourTeamCard14: "/assets/about-assets/png/our_team_card14.png",
  // our advisers
  our_adviser1: "/assets/about-assets/png/our_adviser1.png",
  our_adviser2: "/assets/about-assets/png/our_adviser2.png",
  our_adviser3: "/assets/about-assets/png/our_adviser3.png",
  our_adviser4: "/assets/about-assets/png/our_adviser4.png",
  // News Images
  mainImageNews: "/assets/news-assets/png/NewsHeadImg-1.webp",
  mainImageNewsSecond: "/assets/news-assets/png/NewsHeadImg-2.webp",
  mainImageNews3Rd: "../public/assets/news-assets/png/nih--.png",
  subFirstImageNews: "/assets/news-assets/png/NewsSecondImg-1.webp",
  subSecondImageNews: "/assets/news-assets/png/NewsSecondImg-2.webp",
  subThreeImageNews: "/assets/news-assets/png/NewsSecondImg-3.webp",
  commaImageNews: "/assets/news-assets/png/comma_news.webp",
  plusImageNews: "/assets/news-assets/png/plus__news.webp",
  plusImageNewsSec: "/assets/news-assets/png/Plus__page_news.webp",
  // news
  newsImage1: "/assets/news-assets/png/News1.png",
  newsImage2: "/assets/news-assets/png/News2.png",
  newsImage3: "/assets/news-assets/png/News3.png",
  our_Work_start: "/assets/about-assets/png/our_mission_bottom-start.png",
  newsSideImage: "/assets/news-assets/svg/sideImg.svg",
  FormLeftImg: "/assets/news-assets/svg/FormLeftImg.svg",
};
