export const Images = {
  herostar: "/assets/landing-assets/png/hero-star.png",
  logoImage: "/assets/landing-assets/svg/logo.svg",
  heroImg: "/assets/landing-assets/png/nav-logo.png",
  heroBottomLayer: "/assets/landing-assets/svg/hero-layer-bottom.svg",
  heroLeftPot: "/assets/landing-assets/svg/hero-left-side-pot.svg",
  heroRightPot: "/assets/landing-assets/svg/hero-right-side-pot.svg",
  heroLeftIcon: "/assets/landing-assets/png/hero-left-icon.png",
  heroRightIcon: "/assets/landing-assets/png/hero-right-icon.png",
  workoutChatImg: "/assets/landing-assets/png/workout-chat-img.png",
  partnerIconOne: "/assets/landing-assets/webp/partner-icon-1.webp",
  partnerIconTwo: "/assets/landing-assets/webp/partner-icon-2.webp",
  partnerIconThree: "/assets/landing-assets/webp/partner-icon-3.webp",
  partnerIconFour: "/assets/landing-assets/webp/partner-icon-4.webp",
  partnerIconFive: "/assets/landing-assets/webp/partner-icon-5.webp",
  img_logo_footer: "/assets/landing-assets/svg/logoFooter.svg",
  msgIcon: "/assets/landing-assets/svg/Gmail-logo.svg",
  telIcon: "/assets/landing-assets/svg/tele-logo.svg",
  workoutIcon: "/assets/landing-assets/svg/workout-img.svg",
  trackingFeedbackImg: "/assets/landing-assets/png/tracking-main-img.png",
  checkIcon: "/assets/landing-assets/svg/check_icon.svg",
  feedbackVectorImg: "/assets/landing-assets/png/feedback_top-vecter.png",
  reportingImg: "/assets/landing-assets/png/Report-main-img.png",
  reportingVectorImg:
    "/assets/landing-assets/png/reporting-analytis-bottom-vecter.png",
  trackingImg: "/assets/landing-assets/png/tracking-with-graff.png",
  sliderBgImg: "/assets/landing-assets/png/exercies-slider-bg-img.png",
  sliderPersonOne: "/assets/landing-assets/png/exercies-slider-men.png",
  sliderPersonTwo: "/assets/landing-assets/png/exercies-slider-men2.png",
  clintReview1: "/assets/landing-assets/webp/yoomi-review-by-clint-1.webp",
  commaUp: "/assets/landing-assets/svg/comma_upper.svg",
  commaDown: "/assets/landing-assets/svg/comma_lower.svg",
  starGrup: "/assets/landing-assets/svg/StarGrup.svg",
  ourPlateformSide: "/assets/landing-assets/png/ourplateform-right-img.png",
  plateformBoxVacter: "/assets/landing-assets/png/plateform_box_vacter.png",
  committedLogoHippa: "/assets/landing-assets/webp/committedLogoHippa.webp",
  committedLogoFda: "/assets/landing-assets/webp/committedLogoFDA.webp",
  committedLogoApta: "/assets/landing-assets/webp/committedLogoApta.webp",
  yomiFooterNewesCharacter:
    "/assets/landing-assets/svg/Yommi-News-Character.svg",
  yomiAboutPlusICO: "/assets/landing-assets/svg/Yomi-plus-ico-AboutUs.svg",
  yomiAboutPlusICOsec:
    "/assets/landing-assets/svg/Yomi-plus2nd-ico-AboutUs.svg",
  Yoomi_translatecard_icon:
    "/assets/landing-assets/svg/Yoomi_translatecard_icon.svg",
  footerSideicon: "/assets/landing-assets/svg/footerIcon.svg",
  knowMoreSlide1: "/assets/landing-assets/png/know-more-slide-1.png",
  knowMoreSlide2: "/assets/landing-assets/png/know-more-slide-2.png",
  knowMoreSlide3: "/assets/landing-assets/png/know-more-slide-3.png",
  knowMoreSlide4: "/assets/landing-assets/png/know-more-slide-4.png",
  knowMoreBigSeminar: "/assets/landing-assets/png/know_more-big-img.png",
  knowMoreBigSeminar2: "/assets/landing-assets/png/know_more-big-img-2.png",
  forecastIcon: "/assets/landing-assets/svg/forecastIcon.svg",
  // about pages images
  aboutTopSlider1:"/assets/landing-assets/webp/about-top-slider1.webp",
  aboutTopSlider2:"/assets/landing-assets/webp/about-top-slider2.webp",
};
